### PR TITLE
allow the maximum number of arguments to be configured per parser

### PR DESCRIPTION
**Pull request by yob**
Thanks for a great library, it really helped my little experimental thing (https://github.com/yob/pgredis/) get off the ground.

This is a small change I needed to make in order to get the behaviour I needed. I have some clients that submit up to 1000 values to an `MGET` command, and they were failing due to the hard coded limit of 20 arguments.

This change allows each parser to have a custom maxNumArgs value, which I've used to accept the large `MGET`s I'm receiving. By default the maximum number of arguments accepted from clients is still 20.

I considered opening an issue, but the change was so small I thought I'd open a PR to prompt discussion. I'm happy to close this if it's not suitable for upstream, or adjust it based on feedback.

### CODE REVIEW

**Comment by secmask** [comment]
hello @yob , `MaxNumArg` is a public variable so you can adjust it to whatever value you want at app init. I see your PR update to make it configurable per Parser, is there any reason to support that?

**Comment by yob** [comment]
Huh, I didn't realise that was possible. Thanks for the tip!

I don't need multiple parsers with different `MaxNumArg` values, so this meets my needs. It *does* feel a bit weird to be modifying package-level state like that, but I can live with it if that's your preferred approach. cheers :)

**Comment by secmask** [comment]
@yob I see your code at https://github.com/yob/pgredis/commit/0873ff0d2c4dbd128b8664cdfd176499e9ad37d1#diff-f3a6fabd5339d742e42ee0654c97d72aR198, 
`redisproto.MaxNumArg = 1024` can be put at some where near your `main func`, it's one time job so you don't have to adjust it ever new connection.

**Comment by yob** [comment]
Thanks @secmask

**Pull request closed without merging**
